/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NutDatePicker: typeof import('@nutui/nutui-taro')['DatePicker']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
  }
}
